#!/usr/bin/env ansible-playbook
- name: Add a SNMP Policy
  hosts: apic
  connection: local
  gather_facts: False
  ignore_errors: yes
  vars:
    login_info: &login_info
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
  - name: Add a SNMP Policy to the Pods
    aci_rest:
      <<: *login_info
      method: "post"
      path: "/api/node/mo/uni/fabric/snmppol-snmp_{{item.pod_name}}_ppl.json"
      content:
        '{
            "snmpPol": {
                "attributes": {
                    "dn": "uni/fabric/snmppol-snmp_{{item.pod_name}}_ppl",
                    "name": "snmp_{{item.pod_name}}_ppl",
                    "adminSt": "enabled",
                    "rn": "snmppol-snmp_{{item.pod_name}}_ppl",
                    "status": "{{item.state}}"
                },
                "children": [
                    {
                        "snmpClientGrpP": {
                            "attributes": {
                                "dn": "uni/fabric/snmppol-snmp_{{item.pod_name}}_ppl/clgrp-{{item.policy_snmp_service}}",
                                "name": "{{item.policy_snmp_service}}",
                                "rn": "clgrp-{{item.policy_snmp_service}}",
                                "status": "{{item.state}}"
                            },
                            "children": [
                                {
                                    "snmpClientP": {
                                        "attributes": {
                                            "dn": "uni/fabric/snmppol-snmp_{{item.pod_name}}_ppl/clgrp-{{item.policy_snmp_service}}/client-[{{item.policy_snmp_serverip1}}]",
                                            "name": "{{item.policy_snmp_server1}}",
                                            "addr": "{{item.policy_snmp_serverip1}}",
                                            "rn": "client-[{{item.policy_snmp_serverip1}}]",
                                            "status": "{{item.state}}"
                                        },
                                        "children": []
                                    }
                                },
                                {
                                    "snmpClientP": {
                                        "attributes": {
                                            "dn": "uni/fabric/snmppol-snmp_{{item.pod_name}}_ppl/clgrp-{{item.policy_snmp_service}}/client-[{{item.policy_snmp_serverip2}}]",
                                            "name": "{{item.policy_snmp_server2}}",
                                            "addr": "{{item.policy_snmp_serverip2}}",
                                            "rn": "client-[{{item.policy_snmp_serverip2}}]",
                                            "status": "{{item.state}}"
                                        },
                                        "children": []
                                    }
                                },
                                {
                                    "snmpRsEpg": {
                                        "attributes": {
                                            "tDn": "uni/tn-mgmt/mgmtp-default/oob-default",
                                            "status": "{{item.state}}"
                                        },
                                        "children": []
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "snmpUserP": {
                            "attributes": {
                                "dn": "uni/fabric/snmppol-snmp_{{item.pod_name}}_ppl/user-{{item.policy_snmp_service}}",
                                "name": "{{item.policy_snmp_service}}",
                                "authKey": "Hdkw-{{item.authKey}}",
                                "privType": "{{item.privType}}",
                                "authType": "{{item.authType}}",
                                "privKey": "Hw-{{item.privKey}}",
                                "rn": "user-{{item.policy_snmp_service}}",
                                "status": "{{item.state}}"
                            },
                            "children": []
                        }
                    }
                ]
            }
        }'
    loop: "{{fabric_policy_snmp}}"