#!/usr/bin/env ansible-playbook
- name: Modify Endpoint Controls Policy
  hosts: apic
  connection: local
  gather_facts: False
  ignore_errors: yes
  vars:
    login_info: &login_info
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - name: Modify Endpoint Controls Policy and enable the IP Aging Policy
      aci_rest:
        <<: *login_info
        method: "post"
        path: "/api/node/mo/uni/infra/ipAgingP-default.json"
        content:
          '{
              "epIpAgingP": {
                  "attributes": {
                      "dn": "uni/infra/ipAgingP-default",
                      "adminSt": "enabled"
                  },
                  "children": []
              }
          }'
      delegate_to: localhost